<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXCSoL55\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXCSoL55/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXCSoL55.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXCSoL55\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXCSoL55\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XCSoL55',
    'container.build_id' => '4aa087f3',
    'container.build_time' => 1640055605,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXCSoL55');
